import { Vehicle, SellerListingSubmission, Reservation, PaymentRecord, VehicleInquiry } from '../../types/database';

export const INITIAL_MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1000000-0000-0000-0000-000000000001',
    dealer_name: 'Nairobi Motors Hub',
    seller_type: 'dealer',
    make: 'Toyota',
    model: 'Land Cruiser Prado',
    variant: 'TX 2.7L Petrol',
    year: 2022,
    price: 7299000,
    currency: 'KES',
    mileage: 20245,
    engine_cc: 2700,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'Bronze',
    location: 'Nairobi',
    description: 'Original Kenyan specification demo 2022 Toyota Land Cruiser Prado TX. Low mileage unit featuring 7 leather seats, multi-terrain select, sunroof, and reverse camera.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'CarDuka reference',
    demo_source_id: 'carduka-demo-01',
    category: 'mainstream',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-1-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000001',
        image_url: '',
        display_order: 1,
        is_primary: true,
        source_type: 'demo',
        license_status: 'pending',
        created_at: '2026-01-01'
      }
    ],
    features: ['7 Leather Seats', 'Multi-Terrain Select', 'Sunroof', 'Reverse Camera', 'Push Start'],
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-08-15T10:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000002',
    dealer_name: 'YARDY Imports Hub',
    seller_type: 'dealer',
    make: 'Toyota',
    model: 'Land Cruiser 300',
    variant: 'ZX First Edition 3.3L Twin Turbo',
    year: 2024,
    price: 15050000,
    currency: 'KES',
    mileage: 8000,
    engine_cc: 3300,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'White',
    location: 'Nairobi',
    description: 'Unregistered 2024 Toyota Land Cruiser 300 ZX in White, imported directly via container. Features JBL 14-speaker sound system, head-up display, digital rearview mirror, and crawl control.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'CarDuka reference',
    demo_source_id: 'carduka-demo-02',
    category: 'premium',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-2-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000002',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.29 (2)_Yardy_Imports.jpg',
        display_order: 1,
        is_primary: true,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      }
    ],
    features: ['Container Import', 'ZX First Edition', 'JBL Sound System', 'Head-Up Display', 'Crawl Control'],
    created_at: '2026-08-16T11:00:00Z',
    updated_at: '2026-08-16T11:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000003',
    dealer_name: 'Westlands Premier Cars',
    seller_type: 'dealer',
    make: 'Toyota',
    model: 'Land Cruiser Prado',
    variant: 'Kakadu 2.8L Turbo Diesel',
    year: 2025,
    price: 19500000,
    currency: 'KES',
    mileage: 51,
    engine_cc: 2800,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'Dusty Brown',
    location: 'Nairobi',
    description: 'Brand new 2025 Toyota Land Cruiser Prado Kakadu. Delivery mileage, kinetic dynamic suspension system, rear entertainment screens, and multi-terrain monitor.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'CarDuka reference',
    demo_source_id: 'carduka-demo-03',
    category: 'premium',
    market_status: 'premium_import',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'new',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-3-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000003',
        image_url: '',
        display_order: 1,
        is_primary: true,
        source_type: 'demo',
        license_status: 'pending',
        created_at: '2026-01-01'
      }
    ],
    features: ['Kakadu Top Spec', 'KDSS Suspension', 'Rear Entertainment', 'Panoramic Sunroof'],
    created_at: '2026-08-17T09:30:00Z',
    updated_at: '2026-08-17T09:30:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000004',
    dealer_name: 'Runda Auto Hub',
    seller_type: 'dealer',
    make: 'Toyota',
    model: 'Land Cruiser J70',
    variant: 'Workhorse 2.8L Diesel',
    year: 2024,
    price: 14200000,
    currency: 'KES',
    mileage: 5210,
    engine_cc: 2800,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'White',
    location: 'Nairobi',
    description: 'Rugged 2024 Toyota Land Cruiser J70 Series Workhorse. Heavy duty 4x4, front and rear diff locks, snorkel, factory winch bumper, and tropical cooling system.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'CarDuka reference',
    demo_source_id: 'carduka-demo-04',
    category: 'mainstream',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-4-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000004',
        image_url: '',
        display_order: 1,
        is_primary: true,
        source_type: 'demo',
        license_status: 'pending',
        created_at: '2026-01-01'
      }
    ],
    features: ['Heavy Duty 4x4', 'Front & Rear Diff Locks', 'Factory Snorkel', 'Heavy Duty Winch'],
    created_at: '2026-08-18T14:15:00Z',
    updated_at: '2026-08-18T14:15:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000005',
    dealer_name: 'Lavington Motors',
    seller_type: 'dealer',
    make: 'Toyota',
    model: 'Land Cruiser J200',
    variant: '4.7L V8 Petrol',
    year: 2007,
    price: 3050000,
    currency: 'KES',
    mileage: 171000,
    engine_cc: 4700,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'White',
    location: 'Nairobi',
    description: 'Classic 2007 Toyota Land Cruiser J200 Series V8. Legendary reliability, full leather trim, sunroof, roof rails, and clean Kenyan ownership history.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: false,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'CarDuka reference',
    demo_source_id: 'carduka-demo-05',
    category: 'mainstream',
    market_status: 'locally_available',
    import_eligibility: 'not_applicable',
    steering_position: 'RHD',
    registration_status: 'locally_used',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-5-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000005',
        image_url: '',
        display_order: 1,
        is_primary: true,
        source_type: 'demo',
        license_status: 'pending',
        created_at: '2026-01-01'
      }
    ],
    features: ['4.7L V8 Engine', 'Full Leather Trim', 'Sunroof', '4WD High/Low'],
    created_at: '2026-08-19T08:00:00Z',
    updated_at: '2026-08-19T08:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000006',
    dealer_name: 'Nairobi Motors Hub',
    seller_type: 'dealer',
    make: 'Volkswagen',
    model: 'Tiguan',
    variant: 'R-Line 2.0L TSI AWD',
    year: 2022,
    price: 4850000,
    currency: 'KES',
    mileage: 28000,
    engine_cc: 2000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: 'AWD',
    color: 'White',
    location: 'Nairobi',
    description: 'Fresh import 2022 Volkswagen Tiguan R-Line in Pure White arriving via transporter truck. Features R-Line leather interior, Virtual Cockpit digital dash, panoramic sunroof, and 4Motion AWD.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'YARDY Local Library',
    demo_source_id: 'carduka-demo-12',
    category: 'mainstream',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-12-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000006',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.30_Yardy_Imports.jpg',
        display_order: 1,
        is_primary: true,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      },
      {
        id: 'img-12-2',
        vehicle_id: 'v1000000-0000-0000-0000-000000000006',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.30 (1)_Yardy_Imports.jpg',
        display_order: 2,
        is_primary: false,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      }
    ],
    features: ['Transporter Arrival', 'R-Line Package', 'Virtual Cockpit', 'Panoramic Sunroof', '4Motion AWD'],
    created_at: '2026-08-20T12:00:00Z',
    updated_at: '2026-08-20T12:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000007',
    dealer_name: 'Karen Luxury Automart',
    seller_type: 'dealer',
    make: 'Land Rover',
    model: 'Range Rover',
    variant: 'Vogue L460 3.0L Diesel',
    year: 2022,
    price: 24500000,
    currency: 'KES',
    mileage: 12000,
    engine_cc: 3000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'Black',
    location: 'Nairobi',
    description: 'Exclusive 2022 Land Rover Range Rover Vogue (L460 generation) in Obsidian Black arriving in shipping container. Executive seating, Meridian Signature Sound, soft close doors, and active air suspension.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'YARDY Local Library',
    demo_source_id: 'carduka-demo-13',
    category: 'premium',
    market_status: 'premium_import',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'special_order',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-13-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000007',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.31_Yardy_Imports.jpg',
        display_order: 1,
        is_primary: true,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      }
    ],
    features: ['L460 New Shape', 'Container Import', 'Meridian Signature Sound', 'Soft Close Doors', 'Air Suspension'],
    created_at: '2026-08-21T09:00:00Z',
    updated_at: '2026-08-21T09:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000008',
    dealer_name: 'YARDY Specialty Imports',
    seller_type: 'dealer',
    make: 'Mercedes-Benz',
    model: 'G-Class',
    variant: 'G63 AMG Brabus 800 Widestar',
    year: 2023,
    price: 42000000,
    currency: 'KES',
    mileage: 4200,
    engine_cc: 4000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'Matte Black',
    location: 'Nairobi',
    description: 'Ultra-exclusive 2023 Mercedes-AMG G63 Brabus 800 Widestar edition imported in specialized container. 800 HP V8 BiTurbo, Brabus carbon fiber widebody, sports exhaust, and custom interior.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'YARDY Local Library',
    demo_source_id: 'carduka-demo-14',
    category: 'supercars',
    market_status: 'specialty_import',
    import_eligibility: 'subject_to_verification',
    steering_position: 'RHD',
    registration_status: 'special_order',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-14-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000008',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.31 (2)_Yardy_Imports.jpg',
        display_order: 1,
        is_primary: true,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      },
      {
        id: 'img-14-2',
        vehicle_id: 'v1000000-0000-0000-0000-000000000008',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.31 (1)_Yardy_Imports.jpg',
        display_order: 2,
        is_primary: false,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      }
    ],
    features: ['Brabus 800 Widestar', 'Container Unboxing', '800 HP BiTurbo', 'Carbon Fiber Aero', 'Valvetronic Exhaust'],
    created_at: '2026-08-22T16:00:00Z',
    updated_at: '2026-08-22T16:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000009',
    dealer_name: 'Karen Luxury Automart',
    seller_type: 'dealer',
    make: 'Mercedes-Benz',
    model: 'S-Class',
    variant: 'S500 AMG Line W223',
    year: 2022,
    price: 18500000,
    currency: 'KES',
    mileage: 18000,
    engine_cc: 3000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    drive_type: 'AWD',
    color: 'Black',
    location: 'Nairobi',
    description: 'Pristine 2022 Mercedes-Benz S-Class (W223) S500 4MATIC arriving via sealed container. 3D driver display, Burmester 4D surround sound, rear axle steering, and active ambient lighting.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: false,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'YARDY Local Library',
    demo_source_id: 'carduka-demo-15',
    category: 'premium',
    market_status: 'premium_import',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-15-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000009',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.32_Yardy_Imports.jpg',
        display_order: 1,
        is_primary: true,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      }
    ],
    features: ['W223 Generation', 'Burmester 4D Audio', 'Rear Axle Steering', '3D Cockpit'],
    created_at: '2026-08-23T10:00:00Z',
    updated_at: '2026-08-23T10:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000010',
    dealer_name: 'Westlands Premier Cars',
    seller_type: 'dealer',
    make: 'Subaru',
    model: 'Forester',
    variant: '2.0i-S EyeSight AWD',
    year: 2019,
    price: 3100000,
    currency: 'KES',
    mileage: 58000,
    engine_cc: 2000,
    fuel_type: 'Petrol',
    transmission: 'CVT',
    body_type: 'SUV',
    drive_type: 'AWD',
    color: 'Dark Grey',
    location: 'Nairobi',
    description: 'Clean 2019 Subaru Forester 2.0i-S on car yard lot. Symmetrical AWD, EyeSight driver assist, X-Mode hill descent, panoramic sunroof, and leather upholstery.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: false,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'YARDY Local Library',
    demo_source_id: 'carduka-demo-16',
    category: 'mainstream',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-16-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000010',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.32 (1)_Yardy_Imports.jpg',
        display_order: 1,
        is_primary: true,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      }
    ],
    features: ['Yard Lot Inventory', 'EyeSight Safety', 'Symmetrical AWD', 'X-Mode'],
    created_at: '2026-08-24T11:00:00Z',
    updated_at: '2026-08-24T11:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000011',
    dealer_name: 'Lavington Motors',
    seller_type: 'dealer',
    make: 'BMW',
    model: 'X5',
    variant: 'xDrive30d M Sport G05',
    year: 2021,
    price: 8900000,
    currency: 'KES',
    mileage: 42000,
    engine_cc: 3000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: 'AWD',
    color: 'White',
    location: 'Nairobi',
    description: 'High spec 2021 BMW X5 xDrive30d M Sport on showroom display. Vernasca leather interior, BMW Live Cockpit Pro, panoramic glass roof, and adaptive M suspension.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: false,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'YARDY Local Library',
    demo_source_id: 'carduka-demo-17',
    category: 'premium',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-17-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000011',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.29_Yardy_Imports.jpg',
        display_order: 1,
        is_primary: true,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      }
    ],
    features: ['Indoor Showroom Display', 'M Sport Package', 'Live Cockpit Pro', 'Adaptive M Suspension'],
    created_at: '2026-08-25T14:00:00Z',
    updated_at: '2026-08-25T14:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000012',
    dealer_name: 'Runda Auto Hub',
    seller_type: 'dealer',
    make: 'Volvo',
    model: 'XC60',
    variant: 'B5 AWD Momentum',
    year: 2020,
    price: 5800000,
    currency: 'KES',
    mileage: 38000,
    engine_cc: 2000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: 'AWD',
    color: 'White',
    location: 'Nairobi',
    description: '2020 Volvo XC60 B5 Mild Hybrid AWD. City Safety collision avoidance, Bowers & Wilkins audio, leather seats, and Google infotainment.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: false,
    is_demo: true,
    data_source: 'local_image_library',
    source_reference: 'YARDY Local Library',
    demo_source_id: 'carduka-demo-18',
    category: 'premium',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    images: [
      {
        id: 'img-18-1',
        vehicle_id: 'v1000000-0000-0000-0000-000000000012',
        image_url: '/Car Images/WhatsApp Image 2026-08-31 at 23.30.28 (1)_Yardy_Imports.jpg',
        display_order: 1,
        is_primary: true,
        source_type: 'local_image_library',
        license_status: 'authorized',
        created_at: '2026-01-01'
      }
    ],
    features: ['City Safety Package', 'Bowers & Wilkins Sound', 'Mild Hybrid Tech'],
    created_at: '2026-08-26T09:00:00Z',
    updated_at: '2026-08-26T09:00:00Z'
  }
];

export const INITIAL_MOCK_SUBMISSIONS: SellerListingSubmission[] = [
  {
    id: 'sub-101',
    seller_name: 'Baraka Mwangi',
    seller_phone: '0712345678',
    seller_email: 'bmwangi@gmail.com',
    seller_type: 'private',
    make: 'Subaru',
    model: 'Outback',
    year: 2018,
    registration_number: 'KDH 452X',
    mileage: 78000,
    engine_cc: 2500,
    transmission: 'CVT',
    fuel_type: 'Petrol',
    body_type: 'Station Wagon',
    location: 'Nairobi',
    asking_price: 2800000,
    description: 'Well maintained Subaru Outback 2.5i. Fully serviced at Subaru Kenya. Original logbook available.',
    condition: 'Foreign Used',
    images: [],
    status: 'pending_review',
    created_at: '2026-08-30T14:20:00Z'
  }
];

export const INITIAL_MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'res-9001',
    vehicle_id: 'v1000000-0000-0000-0000-000000000001',
    buyer_name: 'Jane Wambui',
    buyer_phone: '0722998877',
    buyer_email: 'jwambui@yahoo.com',
    amount: 50000,
    currency: 'KES',
    status: 'confirmed',
    expires_at: '2026-09-03T10:00:00Z',
    created_at: '2026-08-31T09:00:00Z',
    vehicle: {
      make: 'Toyota',
      model: 'Land Cruiser Prado',
      year: 2022,
      price: 7299000
    }
  }
];

export const INITIAL_MOCK_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-7001',
    vehicle_id: 'v1000000-0000-0000-0000-000000000001',
    amount: 50000,
    currency: 'KES',
    provider: 'mpesa',
    checkout_request_id: 'ws_CO_31082026_001293',
    mpesa_receipt_number: 'RGH8923KLM',
    phone_number: '0722998877',
    status: 'paid',
    idempotency_key: 'idem-res-9001',
    created_at: '2026-08-31T09:00:00Z',
    updated_at: '2026-08-31T09:01:00Z'
  }
];

export const INITIAL_MOCK_INQUIRIES: VehicleInquiry[] = [
  {
    id: 'inq-5001',
    vehicle_id: 'v1000000-0000-0000-0000-000000000002',
    name: 'Kevin Otieno',
    phone: '0733112233',
    email: 'kotieno@outlook.com',
    message: 'Is the Land Cruiser 300 ZX available for physical inspection tomorrow at YARDY Imports Hub?',
    source: 'web',
    status: 'new',
    created_at: '2026-08-31T11:45:00Z'
  }
];
