import { 
  Vehicle, 
  SellerListingSubmission, 
  Reservation, 
  PaymentRecord, 
  VehicleInquiry, 
  Profile 
} from '../../types/database';
import { buildVehicleImages } from '../utils/imageInventory';

export const INITIAL_MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1000000-0000-0000-0000-000000000001',
    dealer_name: 'Nairobi Motors Hub',
    seller_type: 'dealer',
    make: 'Toyota',
    model: 'Land Cruiser Prado',
    variant: 'TX 2.7L Petrol',
    generation: 'J150 Series (2018-2023)',
    trim: 'TX Package',
    year: 2022,
    price: 7299000,
    currency: 'KES',
    mileage: 20245,
    engine_cc: 2700,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'Bronze',
    exterior_color: 'Bronze Pearl',
    interior_color: 'Black Leather',
    seats: 7,
    doors: 5,
    location: 'Nairobi',
    description: 'Original Kenyan specification 2022 Toyota Land Cruiser Prado TX. Low mileage unit featuring 7 leather seats, multi-terrain select, sunroof, and reverse camera.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDLY Verified Asset',
    category: 'mainstream',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 7100000,
    market_value_high: 7500000,
    estimated_market_value: 7300000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan Automotive Market Analysis 2026',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000001', 'cluster_land_cruiser_200', '2022 Toyota Land Cruiser Prado TX'),
    features: ['7 Leather Seats', 'Multi-Terrain Select', 'Sunroof', 'Reverse Camera', 'Push Start', '4WD High/Low'],
    created_at: '2026-08-15T10:00:00Z',
    updated_at: '2026-08-15T10:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000002',
    dealer_name: 'YARDY Imports Hub',
    seller_type: 'dealer',
    make: 'Toyota',
    model: 'Land Cruiser 300',
    variant: 'ZX First Edition 3.3L Twin Turbo',
    generation: 'J300 Series (2022-2026)',
    trim: 'ZX First Edition',
    year: 2024,
    price: 15050000,
    currency: 'KES',
    mileage: 8000,
    engine_cc: 3300,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'White',
    exterior_color: 'Pearl White',
    interior_color: 'Beige Leather',
    seats: 7,
    doors: 5,
    location: 'Nairobi',
    description: 'Unregistered 2024 Toyota Land Cruiser 300 ZX in White, imported directly via container. Features JBL 14-speaker sound system, head-up display, digital rearview mirror, and crawl control.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'premium',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 14800000,
    market_value_high: 15500000,
    estimated_market_value: 15100000,
    valuation_confidence: 'High',
    valuation_source: 'Nairobi Importers Exchange 2026',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000002', 'cluster_land_cruiser_200', '2024 Toyota Land Cruiser 300 ZX'),
    features: ['Container Import', 'ZX First Edition', 'JBL Sound System', 'Head-Up Display', 'Crawl Control', '360 Camera'],
    created_at: '2026-08-16T11:00:00Z',
    updated_at: '2026-08-16T11:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000003',
    dealer_name: 'Westlands Premier Cars',
    seller_type: 'dealer',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    variant: 'C200 AMG Line W206',
    generation: 'W206 Generation',
    trim: 'AMG Line Night Edition',
    year: 2022,
    price: 6850000,
    currency: 'KES',
    mileage: 18500,
    engine_cc: 1500,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    drive_type: 'RWD',
    color: 'Obsidian Black',
    exterior_color: 'Obsidian Black Metallic',
    interior_color: 'Red & Black Nappa Leather',
    seats: 5,
    doors: 4,
    location: 'Nairobi',
    description: 'Stunning 2022 Mercedes-Benz C200 AMG Line W206. Panoramic glass roof, MBUX portrait touchscreen display, ambient 64-color lighting, Burmester surround sound, and 19-inch AMG multi-spoke alloy wheels.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'premium',
    market_status: 'premium_import',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 6600000,
    market_value_high: 7000000,
    estimated_market_value: 6850000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan Luxury Auto Index',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000003', 'cluster_mercedes_c_class', '2022 Mercedes-Benz C200 AMG Line'),
    features: ['W206 AMG Line', 'Panoramic Sunroof', 'MBUX Portrait Screen', 'Burmester Surround Sound', 'Ambient Lighting'],
    created_at: '2026-08-17T09:30:00Z',
    updated_at: '2026-08-17T09:30:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000004',
    dealer_name: 'Runda Auto Hub',
    seller_type: 'dealer',
    make: 'Porsche',
    model: 'Cayenne',
    variant: '3.0L V6 Turbo AWD',
    generation: 'PO536 (3rd Gen)',
    trim: 'Cayenne S Specs',
    year: 2021,
    price: 13500000,
    currency: 'KES',
    mileage: 24000,
    engine_cc: 3000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: 'AWD',
    color: 'White',
    exterior_color: 'Carrara White Metallic',
    interior_color: 'Espresso Brown Leather',
    seats: 5,
    doors: 5,
    location: 'Nairobi',
    description: 'Immaculate 2021 Porsche Cayenne 3.0L V6 Turbo. Bose Surround Sound system, Sport Chrono Package, adaptive air suspension, matrix LED headlights, and panoramic sunroof.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'premium',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 13200000,
    market_value_high: 13900000,
    estimated_market_value: 13500000,
    valuation_confidence: 'High',
    valuation_source: 'Porsche Approved Market Guide Kenya',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000004', 'cluster_porsche_cayenne', '2021 Porsche Cayenne Turbo'),
    features: ['Sport Chrono Package', 'Bose Surround Sound', 'Adaptive Air Suspension', 'Matrix LED Headlights', 'Panoramic Roof'],
    created_at: '2026-08-18T14:15:00Z',
    updated_at: '2026-08-18T14:15:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000005',
    dealer_name: 'Lavington Motors',
    seller_type: 'dealer',
    make: 'Volkswagen',
    model: 'Golf',
    variant: '2.0L TSI GTI / R-Line Mk8',
    generation: 'Mk8 Generation',
    trim: 'R-Line Package',
    year: 2022,
    price: 4250000,
    currency: 'KES',
    mileage: 21000,
    engine_cc: 2000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Hatchback',
    drive_type: 'FWD',
    color: 'Pure White',
    exterior_color: 'Pure White',
    interior_color: 'Titan Black Fabric/Alcantara',
    seats: 5,
    doors: 5,
    location: 'Nairobi',
    description: 'Hot Hatch 2022 Volkswagen Golf Mk8 R-Line. Digital Cockpit Pro, IQ.LIGHT LED Matrix headlights, Harman Kardon sound system, head-up display, and DCC adaptive chassis control.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'mainstream',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 4100000,
    market_value_high: 4400000,
    estimated_market_value: 4250000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan Hatchback Index 2026',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000005', 'cluster_vw_golf_mk8', '2022 Volkswagen Golf Mk8 R-Line'),
    features: ['Mk8 Digital Cockpit', 'IQ.LIGHT Matrix', 'Harman Kardon Audio', 'DCC Adaptive Chassis', 'R-Line Sport Seats'],
    created_at: '2026-08-19T08:00:00Z',
    updated_at: '2026-08-19T08:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000006',
    dealer_name: 'Nairobi Motors Hub',
    seller_type: 'dealer',
    make: 'Mercedes-Benz',
    model: 'E-Class',
    variant: 'E200 AMG Line W213 Facelift',
    generation: 'W213 Facelift (2021-2023)',
    trim: 'AMG Line Premium Plus',
    year: 2021,
    price: 7950000,
    currency: 'KES',
    mileage: 26000,
    engine_cc: 2000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    drive_type: 'RWD',
    color: 'Iridium Silver',
    exterior_color: 'Iridium Silver Metallic',
    interior_color: 'Black Leather',
    seats: 5,
    doors: 4,
    location: 'Nairobi',
    description: 'Executive 2021 Mercedes-Benz E-Class E200 AMG Line. Dual 12.3-inch widescreen displays, MBUX augmented reality navigation, memory seats, 360 camera, and panoramic sunroof.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'premium',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 7750000,
    market_value_high: 8150000,
    estimated_market_value: 7950000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan Executive Saloon Valuation',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000006', 'cluster_mercedes_e_class', '2021 Mercedes-Benz E200 AMG Line'),
    features: ['Widescreen Cockpit', 'MBUX AR Navigation', 'Panoramic Glass Roof', '360 Surround View', 'Burmester Audio'],
    created_at: '2026-08-20T12:00:00Z',
    updated_at: '2026-08-20T12:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000007',
    dealer_name: 'Karen Luxury Automart',
    seller_type: 'dealer',
    make: 'BMW',
    model: 'X6',
    variant: 'xDrive30d M Sport G06',
    generation: 'G06 Generation',
    trim: 'M Sport Edition',
    year: 2021,
    price: 11200000,
    currency: 'KES',
    mileage: 32000,
    engine_cc: 3000,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: 'AWD',
    color: 'Phytonic Blue',
    exterior_color: 'Phytonic Blue Metallic',
    interior_color: 'Tacora Red Vernasca Leather',
    seats: 5,
    doors: 5,
    location: 'Nairobi',
    description: 'Head-turning 2021 BMW X6 xDrive30d M Sport. Iconic Glow illuminated kidney grille, Sky Lounge panoramic glass roof, Harman Kardon audio, head-up display, and M Sport exhaust system.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'premium',
    market_status: 'premium_import',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 10900000,
    market_value_high: 11500000,
    estimated_market_value: 11200000,
    valuation_confidence: 'High',
    valuation_source: 'BMW Certified Market Kenya',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000007', 'cluster_bmw_x6', '2021 BMW X6 xDrive30d M Sport'),
    features: ['Iconic Glow Grille', 'Sky Lounge Roof', 'Harman Kardon Sound', 'Head-Up Display', 'M Sport Differential'],
    created_at: '2026-08-21T09:00:00Z',
    updated_at: '2026-08-21T09:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000008',
    dealer_name: 'YARDY Specialty Imports',
    seller_type: 'dealer',
    make: 'Toyota',
    model: 'RAV4',
    variant: '2.5L Hybrid G-Package AWD (XA50)',
    generation: 'XA50 (5th Gen)',
    trim: 'G-Package AWD',
    year: 2020,
    price: 4650000,
    currency: 'KES',
    mileage: 34000,
    engine_cc: 2500,
    fuel_type: 'Hybrid',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: 'AWD',
    color: 'Pearl White',
    exterior_color: 'Pearl White Crystal',
    interior_color: 'Black Synthetic Leather',
    seats: 5,
    doors: 5,
    location: 'Nairobi',
    description: 'Fuel efficient 2020 Toyota RAV4 Hybrid AWD G-Package. Toyota Safety Sense 2.0, power tailgate, digital rearview mirror, heated front seats, and blind spot monitor.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'mainstream',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 4500000,
    market_value_high: 4800000,
    estimated_market_value: 4650000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan Hybrid SUV Valuation Index',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000008', 'cluster_rav4_newer', '2020 Toyota RAV4 Hybrid AWD'),
    features: ['E-Four Hybrid AWD', 'Toyota Safety Sense 2.0', 'Power Tailgate', 'Heated Leather Seats', 'Digital Mirror'],
    created_at: '2026-08-22T16:00:00Z',
    updated_at: '2026-08-22T16:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000009',
    dealer_name: 'Karen Luxury Automart',
    seller_type: 'dealer',
    make: 'Mercedes-Benz',
    model: 'S-Class',
    variant: 'S500 AMG Line W223',
    generation: 'W223 Generation',
    trim: 'S500 4MATIC AMG Line',
    year: 2022,
    price: 18500000,
    currency: 'KES',
    mileage: 18000,
    engine_cc: 3000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'Sedan',
    drive_type: 'AWD',
    color: 'Onyx Black',
    exterior_color: 'Onyx Black Metallic',
    interior_color: 'Sienna Brown Exclusive Nappa',
    seats: 5,
    doors: 4,
    location: 'Nairobi',
    description: 'Pristine 2022 Mercedes-Benz S-Class (W223) S500 4MATIC arriving via sealed container. 3D driver display, Burmester 4D surround sound, rear axle steering, and active ambient lighting.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'premium',
    market_status: 'premium_import',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 18100000,
    market_value_high: 18900000,
    estimated_market_value: 18500000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan Super Luxury Market Guide',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000009', 'cluster_s_class', '2022 Mercedes-Benz S-Class S500 W223'),
    features: ['W223 Generation', 'Burmester 4D Audio', 'Rear Axle Steering', '3D Cockpit', 'Soft Close Doors'],
    created_at: '2026-08-23T10:00:00Z',
    updated_at: '2026-08-23T10:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000010',
    dealer_name: 'Westlands Premier Cars',
    seller_type: 'dealer',
    make: 'Audi',
    model: 'Q8',
    variant: '55 TFSI S-Line Quattro',
    generation: '4M Generation',
    trim: 'S-Line Black Edition',
    year: 2021,
    price: 12800000,
    currency: 'KES',
    mileage: 29000,
    engine_cc: 3000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: 'AWD',
    color: 'Daytona Grey',
    exterior_color: 'Daytona Grey Pearl',
    interior_color: 'Valcona Leather Black',
    seats: 5,
    doors: 5,
    location: 'Nairobi',
    description: 'Aggressive 2021 Audi Q8 55 TFSI S-Line Quattro. HD Matrix LED headlights, Bang & Olufsen 3D sound, adaptive air suspension, dual MMI touch response screens, and 22-inch S-Line wheels.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'premium',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 12500000,
    market_value_high: 13100000,
    estimated_market_value: 12800000,
    valuation_confidence: 'High',
    valuation_source: 'Audi Certified Kenya Guide',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000010', 'cluster_audi_q8', '2021 Audi Q8 S-Line Quattro'),
    features: ['S-Line Black Edition', 'Bang & Olufsen 3D', 'HD Matrix LED', 'Adaptive Air Suspension', 'Dual Touchscreen MMI'],
    created_at: '2026-08-24T11:00:00Z',
    updated_at: '2026-08-24T11:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000011',
    dealer_name: 'Lavington Motors',
    seller_type: 'dealer',
    make: 'Toyota',
    model: 'Hiace',
    variant: 'Super GL 2.8L Diesel Van',
    generation: 'H200 Series',
    trim: 'Super GL Dark Prime II',
    year: 2020,
    price: 3850000,
    currency: 'KES',
    mileage: 48000,
    engine_cc: 2800,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'Van / Minibus',
    drive_type: '2WD',
    color: 'Black Metallic',
    exterior_color: 'Black Metallic',
    interior_color: 'Dark Prime Leatherette',
    seats: 5,
    doors: 5,
    location: 'Nairobi',
    description: 'Versatile 2020 Toyota Hiace Super GL Dark Prime II edition. Dual power sliding doors, push start, woodgrain trim, climate control, and Toyota Safety Sense.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: false,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'mainstream',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 3700000,
    market_value_high: 4000000,
    estimated_market_value: 3850000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan Commercial & MPV Index',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000011', 'cluster_hiace', '2020 Toyota Hiace Super GL'),
    features: ['Dark Prime II Spec', 'Dual Power Sliding Doors', 'Push Start', 'Automatic Climate Control', 'Safety Sense'],
    created_at: '2026-08-25T14:00:00Z',
    updated_at: '2026-08-25T14:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000012',
    dealer_name: 'Runda Auto Hub',
    seller_type: 'dealer',
    make: 'Nissan',
    model: 'Patrol',
    variant: 'Y62 V8 Platinum 5.6L',
    generation: 'Y62 Series',
    trim: 'Platinum City Spec',
    year: 2021,
    price: 13800000,
    currency: 'KES',
    mileage: 31000,
    engine_cc: 5600,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: '4WD',
    color: 'Hermosa Blue',
    exterior_color: 'Hermosa Blue Pearl',
    interior_color: 'Tan Quilted Leather',
    seats: 8,
    doors: 5,
    location: 'Nairobi',
    description: 'Dominant 2021 Nissan Patrol Y62 Platinum V8. Hydraulic Body Motion Control (HBMC), Bose 13-speaker audio, rear entertainment screens, and 8 leather seats.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'premium',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 13400000,
    market_value_high: 14200000,
    estimated_market_value: 13800000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan Full-Size 4x4 Market Guide',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000012', 'cluster_patrol_y62', '2021 Nissan Patrol Y62 V8'),
    features: ['HBMC Suspension', '5.6L V8 Engine', 'Bose 13-Speaker Sound', '8 Seats', 'Rear Entertainment'],
    created_at: '2026-08-26T09:00:00Z',
    updated_at: '2026-08-26T09:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000013',
    dealer_name: 'Westlands Premier Cars',
    seller_type: 'dealer',
    make: 'Mercedes-AMG',
    model: 'GLE 53',
    variant: '4MATIC+ Coupe 3.0L Turbo',
    generation: 'C167 Generation',
    trim: 'AMG Night Package',
    year: 2022,
    price: 16500000,
    currency: 'KES',
    mileage: 15000,
    engine_cc: 3000,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_type: 'SUV',
    drive_type: 'AWD',
    color: 'Emerald Green',
    exterior_color: 'Emerald Green Metallic',
    interior_color: 'Black Nappa Leather with Red Stitching',
    seats: 5,
    doors: 5,
    location: 'Nairobi',
    description: 'High performance 2022 Mercedes-AMG GLE 53 Coupe 4MATIC+. AMG Performance exhaust, Air Body Control suspension, Burmester surround sound, panoramic roof, and 22-inch AMG forged alloy wheels.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: true,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'premium',
    market_status: 'premium_import',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 16000000,
    market_value_high: 17000000,
    estimated_market_value: 16500000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan AMG Performance Index',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000013', 'cluster_mercedes_gle_coupe', '2022 Mercedes-AMG GLE 53 Coupe'),
    features: ['AMG Performance Exhaust', 'Air Body Control', 'Burmester Audio', '22-inch Forged Wheels', 'Panoramic Roof'],
    created_at: '2026-08-27T10:00:00Z',
    updated_at: '2026-08-27T10:00:00Z'
  },
  {
    id: 'v1000000-0000-0000-0000-000000000014',
    dealer_name: 'Lavington Motors',
    seller_type: 'dealer',
    make: 'Mazda',
    model: 'Demio',
    variant: '1.5L SkyActiv-D XD Touring',
    generation: 'DJ Series',
    trim: 'XD Touring L Package',
    year: 2020,
    price: 1850000,
    currency: 'KES',
    mileage: 42000,
    engine_cc: 1500,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_type: 'Hatchback',
    drive_type: '2WD',
    color: 'Soul Red Crystal',
    exterior_color: 'Soul Red Crystal Metallic',
    interior_color: 'Off-White Leather',
    seats: 5,
    doors: 5,
    location: 'Nairobi',
    description: 'Fuel efficient and stylish 2020 Mazda Demio SkyActiv-D. Leather seats, head-up display, i-Activesense safety package, paddle shifters, and alloy wheels.',
    status: 'active',
    verification_status: 'verified',
    logbook_verified: true,
    featured: false,
    is_demo: false,
    data_source: 'local_image_library',
    source_reference: 'YARDY Verified Asset',
    category: 'mainstream',
    market_status: 'importable_subject_to_requirements',
    import_eligibility: 'eligible',
    steering_position: 'RHD',
    registration_status: 'import',
    vehicle_match_status: 'verified',
    market_value_low: 1780000,
    market_value_high: 1920000,
    estimated_market_value: 1850000,
    valuation_confidence: 'High',
    valuation_source: 'Kenyan Compact Hatchback Index',
    images: buildVehicleImages('v1000000-0000-0000-0000-000000000014', 'cluster_demio', '2020 Mazda Demio SkyActiv-D'),
    features: ['SkyActiv-D Turbo Diesel', 'Leather Interior', 'Head-Up Display', 'i-Activesense Safety', 'Alloy Wheels'],
    created_at: '2026-08-28T09:00:00Z',
    updated_at: '2026-08-28T09:00:00Z'
  }
];

export const INITIAL_MOCK_SUBMISSIONS: SellerListingSubmission[] = [
  {
    id: 'sub-101',
    seller_name: 'Baraka Mwangi',
    seller_phone: '0712345678',
    seller_email: 'bmwangi@gmail.com',
    seller_type: 'private',
    make: 'Subaru',
    model: 'Outback',
    year: 2018,
    registration_number: 'KDH 452X',
    mileage: 78000,
    engine_cc: 2500,
    transmission: 'CVT',
    fuel_type: 'Petrol',
    body_type: 'Station Wagon',
    location: 'Nairobi',
    asking_price: 2800000,
    description: 'Well maintained Subaru Outback 2.5i. Fully serviced at Subaru Kenya. Original logbook available.',
    condition: 'Foreign Used',
    images: ['/Car Images/WhatsApp Image 2026-09-01 at 09.47.24 (1).jpeg'],
    status: 'pending_review',
    created_at: '2026-08-30T14:20:00Z'
  }
];

export const INITIAL_MOCK_RESERVATIONS: Reservation[] = [
  {
    id: 'res-9001',
    vehicle_id: 'v1000000-0000-0000-0000-000000000001',
    buyer_name: 'Jane Wambui',
    buyer_phone: '0722998877',
    buyer_email: 'jwambui@yahoo.com',
    amount: 50000,
    currency: 'KES',
    status: 'confirmed',
    expires_at: '2026-09-03T10:00:00Z',
    created_at: '2026-08-31T09:00:00Z',
    vehicle: {
      make: 'Toyota',
      model: 'Land Cruiser Prado',
      year: 2022,
      price: 7299000
    }
  }
];

export const INITIAL_MOCK_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-7001',
    vehicle_id: 'v1000000-0000-0000-0000-000000000001',
    amount: 50000,
    currency: 'KES',
    provider: 'mpesa',
    checkout_request_id: 'ws_CO_31082026_001293',
    mpesa_receipt_number: 'RGH8923KLM',
    phone_number: '0722998877',
    status: 'paid',
    idempotency_key: 'idem-res-9001',
    created_at: '2026-08-31T09:00:00Z',
    updated_at: '2026-08-31T09:01:00Z'
  }
];

export const INITIAL_MOCK_INQUIRIES: VehicleInquiry[] = [
  {
    id: 'inq-5001',
    vehicle_id: 'v1000000-0000-0000-0000-000000000002',
    name: 'Kevin Otieno',
    phone: '0733112233',
    email: 'kotieno@outlook.com',
    message: 'Is the Land Cruiser 300 ZX available for physical inspection tomorrow at YARDY Imports Hub?',
    source: 'web',
    status: 'new',
    created_at: '2026-08-31T11:45:00Z'
  }
];

export const INITIAL_MOCK_BUYERS: Profile[] = [
  {
    id: 'buyer-001',
    email: 'buyer@yardly.co.ke',
    full_name: 'Maina Kamau',
    phone: '+254 712 987 654',
    role: 'buyer',
    status: 'active',
    created_at: '2026-06-15T08:00:00Z'
  },
  {
    id: 'buyer-002',
    email: 'grace.njeri@gmail.com',
    full_name: 'Grace Njeri',
    phone: '+254 720 112 233',
    role: 'buyer',
    status: 'active',
    created_at: '2026-07-01T10:30:00Z'
  }
];

export const INITIAL_MOCK_SELLERS: Profile[] = [
  {
    id: 'seller-001',
    email: 'sales@nairobimotors.co.ke',
    full_name: 'Nairobi Motors Hub',
    phone: '+254 700 888 999',
    role: 'seller',
    seller_type: 'dealer',
    business_name: 'Nairobi Motors Hub Ltd',
    status: 'active',
    created_at: '2026-05-10T12:00:00Z'
  },
  {
    id: 'seller-002',
    email: 'baraka@yardlyimports.co.ke',
    full_name: 'YARDY Imports Hub',
    phone: '+254 711 223 344',
    role: 'seller',
    seller_type: 'importer',
    business_name: 'YARDY Premium Imports',
    status: 'active',
    created_at: '2026-04-20T09:15:00Z'
  }
];

export const INITIAL_MOCK_AUCTIONS: any[] = [
  {
    id: 'auc-001',
    vehicle_id: 'v1000000-0000-0000-0000-000000000001',
    starting_bid: 6500000,
    current_bid: 7100000,
    minimum_increment: 50000,
    bid_count: 5,
    start_time: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    end_time: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
    status: 'live',
    created_at: '2026-08-30T10:00:00Z',
    bids: [
      { id: 'b-1', auction_id: 'auc-001', buyer_id: 'buyer-001', buyer_name: 'Maina Kamau', buyer_email: 'buyer@yardly.co.ke', amount: 6600000, created_at: '2026-08-30T11:00:00Z' },
      { id: 'b-2', auction_id: 'auc-001', buyer_id: 'buyer-002', buyer_name: 'Grace Njeri', buyer_email: 'grace.njeri@gmail.com', amount: 6800000, created_at: '2026-08-30T14:00:00Z' },
      { id: 'b-3', auction_id: 'auc-001', buyer_id: 'buyer-001', buyer_name: 'Maina Kamau', buyer_email: 'buyer@yardly.co.ke', amount: 7100000, created_at: '2026-08-31T09:00:00Z' }
    ]
  },
  {
    id: 'auc-002',
    vehicle_id: 'v1000000-0000-0000-0000-000000000002',
    starting_bid: 14000000,
    current_bid: 14500000,
    minimum_increment: 100000,
    bid_count: 3,
    start_time: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    end_time: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
    status: 'ending_soon',
    created_at: '2026-08-30T12:00:00Z',
    bids: [
      { id: 'b-4', auction_id: 'auc-002', buyer_id: 'buyer-002', buyer_name: 'Grace Njeri', buyer_email: 'grace.njeri@gmail.com', amount: 14500000, created_at: '2026-08-31T08:30:00Z' }
    ]
  }
];

export const INITIAL_MOCK_TRADE_INS: any[] = [
  {
    id: 'trd-101',
    reference_id: 'TRD-2026-8921',
    full_name: 'Daniel Kiprop',
    email: 'dkiprop@gmail.com',
    phone: '+254 722 554 433',
    make: 'Toyota',
    model: 'Harrier',
    year: 2017,
    mileage: 65000,
    registration_status: 'locally_registered',
    transmission: 'Automatic',
    fuel_type: 'Hybrid',
    condition: 'Foreign Used',
    location: 'Nairobi',
    expected_value: 3200000,
    description: 'Leather interior, low mileage 2017 Harrier hybrid in mint condition. Seeking trade-in for Prado TX.',
    images: [],
    status: 'under_review',
    created_at: '2026-08-29T14:30:00Z'
  }
];

export const INITIAL_MOCK_IMPORTS: any[] = [
  {
    id: 'imp-101',
    reference_number: 'IMP-2026-4410',
    full_name: 'Dr. Sarah Odhiambo',
    email: 'sodhiambo@health.go.ke',
    phone: '+254 733 998 877',
    country: 'Kenya',
    preferred_source_country: 'Japan',
    make: 'Lexus',
    model: 'RX450h',
    year_min: 2020,
    budget: 6800000,
    preferred_specs: 'White exterior, Tan leather interior, Panoramic roof, Sunroof, 360 camera.',
    shipping_preference: 'RoRo',
    additional_requirements: 'Requesting pre-shipment QISJ inspection certificate.',
    status: 'sourcing',
    assigned_to: 'YARDY Import Logistics Team',
    created_at: '2026-08-28T09:00:00Z'
  }
];

export const INITIAL_MOCK_FAVORITES: any[] = [
  {
    id: 'fav-001',
    user_id: 'buyer-001',
    vehicle_id: 'v1000000-0000-0000-0000-000000000001',
    created_at: '2026-08-30T10:00:00Z'
  }
];

export const INITIAL_MOCK_NOTIFICATIONS: any[] = [
  {
    id: 'notif-001',
    user_id: 'buyer-001',
    type: 'auction_bid',
    title: 'Bid Placed Successfully',
    message: 'Your bid of KES 7,100,000 for 2022 Toyota Land Cruiser Prado TX was recorded.',
    read: false,
    link: '/auction',
    created_at: '2026-08-31T09:00:00Z'
  },
  {
    id: 'notif-002',
    user_id: 'buyer-001',
    type: 'trade_in_status',
    title: 'Trade-In Request Under Review',
    message: 'Your Trade-In request TRD-2026-8921 is currently being evaluated by our team.',
    read: true,
    link: '/account',
    created_at: '2026-08-29T15:00:00Z'
  }
];
